name: cautionem
ui: mocha-bdd
html: test/template.html
scripts:
  - "//polyfill.io"
  - "jam/require.js"
  - "test/zrequire.js"

browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 9..latest
