name: cautionem
ui: mocha-bdd
html: test/template.html
scripts:
  - "jam/require.js"
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 7..latest
